# Generated by Django 5.0.7 on 2024-10-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0002_studentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'Advanced object oriented programming'), ('PFSD', 'Python full stack development'), ('AIML', 'Artificial intelligence and machine learning'), ('MP', 'Mathematical programming')], max_length=50)),
                ('section', models.CharField(choices=[('S11', 'Section 11'), ('S12', 'Section 12'), ('S13', 'Section 13'), ('S14', 'Section 14'), ('S15', 'Section 15')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
    ]
